version: '3.8'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: docker-ninja-api
    ports:
      - '4000:4000'
    volumes:
      - '/app/node_modules'
      - './api:/app'
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: docker-ninja-web
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
