import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="p-4">
          <div className="container">
            <ul className="flex items-center gap-5 cursor-pointer">
              <li className="hover:text-gray-400">
                <Link href="/">Home</Link>
              </li>
              <li className="hover:text-gray-400">
                <Link href="/posts">Post</Link>
              </li>
            </ul>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
